from __future__ import annotations
from typing import Any, Protocol
from domain.models import RiskLevel

class ApprovalPort(Protocol):
    def authorize_or_request(self, action_type: str, payload: dict[str, Any], risk: RiskLevel, token: str = "", legacy_approvals: list[str] | None = None) -> tuple[bool, dict[str, Any] | None]: ...
    def approve(self, request_id: str) -> str: ...
    def deny(self, request_id: str) -> None: ...
    def list(self, status: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
