from __future__ import annotations
from typing import Protocol

class ArtifactPort(Protocol):
    def write_text(self, name: str, content: str, *, kind: str = "text") -> dict: ...
    def read_text(self, name: str, max_chars: int = 100_000) -> str: ...
    def list(self, limit: int = 100) -> list[dict]: ...
