from __future__ import annotations

from typing import Protocol

from domain.browser_session import BrowserSessionSnapshot


class BrowserSessionStorePort(Protocol):
    def save(self, snapshot: BrowserSessionSnapshot) -> None: ...
    def load(self, session_id: str) -> BrowserSessionSnapshot | None: ...
    def delete(self, session_id: str) -> None: ...
    def purge_expired(self, now_epoch: float) -> int: ...
