from __future__ import annotations

from typing import Any, Protocol

from domain.browser import BrowserFrame, BrowserState


class BrowserProvider(Protocol):
    async def create_session(self, session_id: str, *, viewport: dict[str, int]) -> BrowserState: ...
    async def has_session(self, session_id: str) -> bool: ...
    async def navigate(self, session_id: str, url: str) -> BrowserState: ...
    async def view(self, session_id: str) -> BrowserState: ...
    async def click(self, session_id: str, selector: str) -> BrowserState: ...
    async def input(self, session_id: str, selector: str, value: str) -> BrowserState: ...
    async def press_key(self, session_id: str, key: str) -> BrowserState: ...
    async def scroll(self, session_id: str, delta_x: float, delta_y: float) -> BrowserState: ...
    async def select_option(self, session_id: str, selector: str, value: str) -> BrowserState: ...
    async def back(self, session_id: str) -> BrowserState: ...
    async def forward(self, session_id: str) -> BrowserState: ...
    async def refresh(self, session_id: str) -> BrowserState: ...
    async def get_tabs(self, session_id: str) -> BrowserState: ...
    async def switch_tab(self, session_id: str, tab_id: str) -> BrowserState: ...
    async def close_tab(self, session_id: str, tab_id: str) -> BrowserState: ...
    async def click_at(self, session_id: str, x: float, y: float) -> BrowserState: ...
    async def insert_text(self, session_id: str, text: str) -> BrowserState: ...
    async def capture_frame(self, session_id: str) -> BrowserFrame: ...
    async def close_session(self, session_id: str) -> None: ...
    async def close_all(self) -> None: ...
    async def probe(self) -> dict[str, Any]: ...


class CdpBrowserProvider(Protocol):
    """Optional capability interface for Chromium-specific diagnostics without polluting BrowserProvider."""

    async def cdp_snapshot(self, session_id: str) -> dict[str, Any]: ...
