from __future__ import annotations
from typing import Protocol

class MemoryPort(Protocol):
    def upsert(self, key: str, value: str) -> None: ...
    def search(self, query: str, limit: int = 8) -> list[str]: ...
    def all(self, limit: int = 100) -> list[dict]: ...
