from __future__ import annotations

from typing import Protocol

from ports.provider_telemetry import ProviderCallMetrics


class TokenBudgetPort(Protocol):
    def estimate_tokens(self, char_count: int) -> int: ...
    def preflight_delay_seconds(self, session_id: str, estimated_input_tokens: int) -> float: ...
    def observe(self, metrics: ProviderCallMetrics) -> None: ...
    def context_budget_chars(self, session_id: str, configured_chars: int) -> int: ...
    def snapshot(self, session_id: str) -> dict: ...
