from __future__ import annotations
from typing import Any, Protocol
from domain.models import ToolResult

class ToolPort(Protocol):
    name: str
    description: str
    async def run(self, arguments: dict[str, Any]) -> ToolResult: ...
    def schema(self) -> dict[str, Any]: ...

class ToolRegistryPort(Protocol):
    def register(self, tool: ToolPort) -> None: ...
    async def call(self, name: str, arguments: dict[str, Any], *, session_id: str = "") -> ToolResult: ...
    def describe(self) -> str: ...
    @property
    def names(self) -> list[str]: ...
